//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceAgenda.UnitTest.ServiceAgenda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtistWS", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class ArtistWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeNaissanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GiudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeNaissance {
            get {
                return this.DateDeNaissanceField;
            }
            set {
                if ((this.DateDeNaissanceField.Equals(value) != true)) {
                    this.DateDeNaissanceField = value;
                    this.RaisePropertyChanged("DateDeNaissance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Giud {
            get {
                return this.GiudField;
            }
            set {
                if ((this.GiudField.Equals(value) != true)) {
                    this.GiudField = value;
                    this.RaisePropertyChanged("Giud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EvenementWS", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class EvenementWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[] ArtistesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TarifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[] Artistes {
            get {
                return this.ArtistesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistesField, value) != true)) {
                    this.ArtistesField = value;
                    this.RaisePropertyChanged("Artistes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Tarif {
            get {
                return this.TarifField;
            }
            set {
                if ((this.TarifField.Equals(value) != true)) {
                    this.TarifField = value;
                    this.RaisePropertyChanged("Tarif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LieuWS", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class LieuWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NombrePlacesTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> _pourcentageCommissionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombrePlacesTotal {
            get {
                return this.NombrePlacesTotalField;
            }
            set {
                if ((this.NombrePlacesTotalField.Equals(value) != true)) {
                    this.NombrePlacesTotalField = value;
                    this.RaisePropertyChanged("NombrePlacesTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> _pourcentageCommission {
            get {
                return this._pourcentageCommissionField;
            }
            set {
                if ((this._pourcentageCommissionField.Equals(value) != true)) {
                    this._pourcentageCommissionField = value;
                    this.RaisePropertyChanged("_pourcentageCommission");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningElementWS", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class PlanningElementWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS MonEvementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS MonLieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPlacesReserveesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((this.DateDebutField.Equals(value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFin {
            get {
                return this.DateFinField;
            }
            set {
                if ((this.DateFinField.Equals(value) != true)) {
                    this.DateFinField = value;
                    this.RaisePropertyChanged("DateFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS MonEvement {
            get {
                return this.MonEvementField;
            }
            set {
                if ((object.ReferenceEquals(this.MonEvementField, value) != true)) {
                    this.MonEvementField = value;
                    this.RaisePropertyChanged("MonEvement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS MonLieu {
            get {
                return this.MonLieuField;
            }
            set {
                if ((object.ReferenceEquals(this.MonLieuField, value) != true)) {
                    this.MonLieuField = value;
                    this.RaisePropertyChanged("MonLieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPlacesReservees {
            get {
                return this.NbPlacesReserveesField;
            }
            set {
                if ((this.NbPlacesReserveesField.Equals(value) != true)) {
                    this.NbPlacesReserveesField = value;
                    this.RaisePropertyChanged("NbPlacesReservees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilisateurWS", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAgenda.Business")]
    [System.SerializableAttribute()]
    public partial class UtilisateurWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgenda.IServiceAgenda")]
    public interface IServiceAgenda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetData", ReplyAction="http://tempuri.org/IServiceAgenda/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetData", ReplyAction="http://tempuri.org/IServiceAgenda/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAgenda/GetDataUsingDataContractResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType GetDataUsingDataContract(WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAgenda/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType> GetDataUsingDataContractAsync(WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllArtistes", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllArtistesResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[] GetAllArtistes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllArtistes", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllArtistesResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[]> GetAllArtistesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllEvents", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllEventsResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS[] GetAllEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllEvents", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllEventsResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS[]> GetAllEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllLieux", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllLieuxResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS[] GetAllLieux();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllLieux", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllLieuxResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS[]> GetAllLieuxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllPlanningElements", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllPlanningElementsResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.PlanningElementWS[] GetAllPlanningElements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllPlanningElements", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllPlanningElementsResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.PlanningElementWS[]> GetAllPlanningElementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllUsers", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllUsersResponse")]
        WcfServiceAgenda.UnitTest.ServiceAgenda.UtilisateurWS[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgenda/GetAllUsers", ReplyAction="http://tempuri.org/IServiceAgenda/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.UtilisateurWS[]> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAgendaChannel : WcfServiceAgenda.UnitTest.ServiceAgenda.IServiceAgenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAgendaClient : System.ServiceModel.ClientBase<WcfServiceAgenda.UnitTest.ServiceAgenda.IServiceAgenda>, WcfServiceAgenda.UnitTest.ServiceAgenda.IServiceAgenda {
        
        public ServiceAgendaClient() {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType GetDataUsingDataContract(WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType> GetDataUsingDataContractAsync(WcfServiceAgenda.UnitTest.ServiceAgenda.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[] GetAllArtistes() {
            return base.Channel.GetAllArtistes();
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.ArtistWS[]> GetAllArtistesAsync() {
            return base.Channel.GetAllArtistesAsync();
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS[] GetAllEvents() {
            return base.Channel.GetAllEvents();
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.EvenementWS[]> GetAllEventsAsync() {
            return base.Channel.GetAllEventsAsync();
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS[] GetAllLieux() {
            return base.Channel.GetAllLieux();
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.LieuWS[]> GetAllLieuxAsync() {
            return base.Channel.GetAllLieuxAsync();
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.PlanningElementWS[] GetAllPlanningElements() {
            return base.Channel.GetAllPlanningElements();
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.PlanningElementWS[]> GetAllPlanningElementsAsync() {
            return base.Channel.GetAllPlanningElementsAsync();
        }
        
        public WcfServiceAgenda.UnitTest.ServiceAgenda.UtilisateurWS[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WcfServiceAgenda.UnitTest.ServiceAgenda.UtilisateurWS[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
